blog/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('post.urls')),
]

post/urls.py
'''
Urls module
'''

from django.urls import path

from post.views import post as post_views
from post.views import comment as comment_views

app_name='post'

urlpatterns = [  
    path(r'', post_views.HomeView.as_view(),
        name='index'),
    path(r'new', post_views.PostView.as_view(),
        name='new'),
    path(r'edit/(?P<id>\d+)/$', post_views.EditPostVIew.as_view(),
        name='edit'),
    path(r'delete/(?P<id>\d+)/$', post_views.DeletePostView.as_view(),
        name='delete'),
    path(r'list/(?P<id>\d+)/$', comment_views.CommentListView.as_view(),
        name='list'),
    
]

post/models.py
from django.db import models
from django.contrib.auth.models import User

from src.model import BaseModel
from src.validators import IS_ALPHAVALIDATOR

# Create your models here.

class PostBlog(BaseModel):
    
    title = models.CharField('Título',max_length=200)
    body = models.TextField('Texto del post')

    def __str__(self):
        return self.title


class Comment(BaseModel):

    post_blog = models.ForeignKey(PostBlog, verbose_name='Post',on_delete=models.CASCADE )
    commentary = models.TextField('Comentario', max_length=500)
    name = models.CharField('Nombre', max_length=150, validators=[IS_ALPHAVALIDATOR])
    
    def __str__(self):
        return self.commentary

post/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User

from post.models import PostBlog, Comment


class PostForm(ModelForm):
                    
            
    class Meta:

        '''
        Contiene el modelo que necesita el template
        '''
        model = PostBlog
        fields = ['title', 'body']

class CommentForm(ModelForm):

    class Meta:
        
        '''
        Contiene el modelo que necesita el template
        '''
        model = Comment
        fields = ['post_blog', 'commentary', 'name']

post/views/comment.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.views.generic import View

from post.models import PostBlog, Comment
from post.forms import CommentForm

class CommentListView(View):

    template_name = 'blog/comment/list.html'

    def get_post(self, id_post):

        try:
            post = PostBlog.objects.get(id=id_post)   
        except PostBlog.DoesNotExist:
            post = None
        return post

    def get_commentary(self, id_post):

        try:
            comments = Comment.objects.filter(post_blog=id_post).order_by('-created_at')  
        except Comment.DoesNotExist:
            comments = None
        return comments

    def get(self, request, *args, **kwargs):
        """
        Muestra el formulario 
        """
        if not kwargs['id']:
            messages.error(request, 'Post no encontrado')        
            return HttpResponseRedirect(reverse('post:index'))  
        
        post = self.get_post(kwargs['id']) 
        if not post:
            messages.error(request, 'Post no encontrado')        
            return HttpResponseRedirect(reverse('post:index'))
        comments = self.get_commentary(kwargs['id'])

        form_comment = CommentForm(initial={'post_blog':kwargs['id']})
        output = {
            'post': post,
            'form': form_comment,
            'comments': comments, 
        }
        return render(request, self.template_name, output)


    def post(self, request, *args, **kwargs):
        """
        Muestra el formulario 
        """
        form = CommentForm(request.POST)
        if not form.is_valid():
            post = self.get_post(kwargs['id']) 
            comments = self.get_commentary(kwargs['id'])
            messages.error(request, 'Valide los errores')
            output = {
                'post': post,
                'form': form,
                'comments': comments,
            }
            return render(request, self.template_name, output)
        
        form.save()
        messages.success(request, 'Comentario registrado exitosamente')        
        return HttpResponseRedirect(reverse('post:list', kwargs={'id':kwargs['id']}))

post/views/post.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.views.generic import View

from post.models import PostBlog, Comment
from post.forms import PostForm


class HomeView(View):
    '''
    '''
    template_name = 'blog/index.html'

    def get(self, request):
        '''
        Método get
        '''
        data = PostBlog.objects.all().order_by('-created_at')
        output = {
            'results': data,
        }
        return render(request, self.template_name, output)


class PostView (View):

    template_name = 'blog/post/post.html'

    def get(self, request, *args, **kwargs):
        """
        Muestra el formulario 
        """
        form = PostForm()
        output = {
            'form': form,
        }
        return render(request, self.template_name, output)


    def post(self, request, *args, **kwargs):
        """
        Muestra el formulario 
        """
        form = PostForm(request.POST)
        if not form.is_valid():
            messages.error(request, 'Valide los errores')
            output = {
                'form': form,
            }
            return render(request, self.template_name, output)
        
        form.save()
        messages.success(request, 'Post registrado exitosamente')        
        return HttpResponseRedirect(reverse('post:index'))


class EditPostVIew(View):

    template_name = 'blog/post/edit.html'

    def get(self, request, *args, **kwargs):
        """
        Muestra el formulario 
        """
        if not kwargs['id']:
            messages.error(request, 'Post no encontrado')        
            return HttpResponseRedirect(reverse('post:index'))
        
        post = PostBlog.objects.get(id=kwargs['id'])
        form = PostForm(instance=post)        
        output = {
            'form': form,

        }
        return render(request, self.template_name, output)


    def post(self, request, *args, **kwargs):
        """
        Muestra el formulario 
        """
        post = PostBlog.objects.get(id=kwargs['id'])
        form = PostForm(request.POST, instance=post)
        if not form.is_valid():
            messages.error(request, 'Valide los errores')
            output = {
                'form': form,

            }
            return render(request, self.template_name, output)
        
        form.save()
        messages.success(request, 'Post actualizado exitosamente')        
        return HttpResponseRedirect(reverse('post:index'))

class DeletePostView(View):

    template_name = 'blog/post/delete.html'

    def get(self, request, *args, **kwargs):
        """
        Muestra el formulario 
        """
        if not kwargs['id']:
            messages.error(request, 'Post no encontrado')   
            return HttpResponseRedirect(reverse('post:index'))    
        output = {
            'id': kwargs['id'],
        }
        return render(request, self.template_name, output)


    def post(self, request, *args, **kwargs):
        """
        ELimina el post
        """        
        if not request.POST.get('id-delete'):
            messages.error(request, 'Post no encontrado')       
            return HttpResponseRedirect(reverse('post:index'))
        
        post = PostBlog.objects.get(id=request.POST.get('id-delete'))
        # se elimina lógicamente desde el src.model.py método delete
        post.delete()
        comments = Comment.objects.filter(post_blog=request.POST.get('id-delete'))
        if comments:
            for comment in comments:
                comment.delete()

        messages.success(request, 'Post eliminado exitosamente')        
        return HttpResponseRedirect(reverse('post:index'))

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head >

<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}  {% endblock %} Blog</title>
    <link rel="SHORTCUT ICON" href="{% static 'images/favicon.png' %}?v=2">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/my-site.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
 
</head>

<body>

	<header>
        <img class="header"alt="">
         <div class="">
            {% if not request.user %}
             <p class="user" href="">Usuario: {{request.user}} </p>
            {% endif %}
         </div>
   </header>
   <div class="clearfix clear2"></div>
   <nav class="navbar navbar-inverse">
       <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
       </div>
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
           <ul class="nav navbar-nav navbar-right">
               <li><a href="{% url 'post:index' %}">Inicio</a></li>
               <li><a href="{% url 'post:new' %}">Nuevo Post</a></li>
           </ul>
       </div>
   </nav>
   <div class="col-md-12 sub-body">
   {% if messages %}
       {% for message in messages%}
       <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}"><a class="close" data-dismiss="alert" href="#">&times;</a>{{ message|safe }}</div>
       {% endfor %}
   {% endif %}
   {% block content %}
   <h4>Bloque de contenido</h4>
   {% endblock %}
   </div>
   <div class="footer">      
       <footer>
           Juan Esteban Castaño Mera - 2018
       </footer>
   </div>

   <script>
      
   </script>
   {% block script %}
   <script></script>
   {% endblock %}
</body>

</html>

templates/blog/comment/list.html
{% extends "base/base.html" %} {% load widget_tweaks %}  {% load static %} {% load application_extras %}
{% block content %}
<div class="container-fluid">
    <form method="POST" style="width:100%;" novalidate>
        {% csrf_token %}
        <div class="container text-justify">
            <br/>
            <h2>{{post.title}} </h2>
            <hr>
            <p>{{post.body}}</p>            
            <br>
        </div>
        <br>
        <br>
        <div class="container text-justify">  
            <h3>Comentarios</h3>
            {% for comment in comments %}               
                                
                <hr>
                <h4>{{comment.name}}  </h4>
                <span>{{comment.created_at|date:'Y-m-d h:s'}}</span>
                <br><br>
                <p>{{comment.commentary}}</p>            
                <br>
                
            {% endfor %}
        </div>
        <div class="container text-justify">                
            <div class="col-md-8">
                <h4>Comentar</h4>
                <hr>                            
                    <div class="col-md-8 column blog" >                           
                        {{ form.post_blog.as_hidden }}                            
                    </div>    
                    <div class="col-md-8 column" style="text-align:left">
                        <label class="control-label" >{{ form.commentary.label }}{{ form.commentary|is_required:"* "}} </label>
                        {{ form.commentary|add_class:"form-control text-left" }}
                        
                        {% for error in form.commentary.errors %}
                            <div class="error">- {{ error }}</div>
                        {% endfor %}
                    </div>
                    <br/><br/>
                    <div class="col-md-8 column" style="text-align:left">
                            <label class="control-label" >{{ form.name.label }}{{ form.name|is_required:"* "}} </label>
                            {{ form.name|add_class:"form-control text-left" }}
                            
                            {% for error in form.name.errors %}
                                <div class="error" >- {{ error }}</div>
                            {% endfor %}
                        </div>
                    
                    <br clear="all"/><br clear="all"/>
                    
                <br>                
                <div class="col-md-8 column" >
                    <a href="{% url 'post:index'%}" class="btn btn-primary">Regresar</a>
                    <button class="btn btn-success" type="submit">Guardar Comentario</button>
                </div>
            </div>
        </div>
    </form>
   
</div>
<script type="text/javascript"> 
</script>
{% endblock %}

templates/blog/index.html
{% extends "base/base.html" %} {% load widget_tweaks %}  {% load static %}
{% block content %}
<div class="container-fluid">
    <h2>Blog  </h2>
    <div class="row">
        <form method="GET" style="width:100%;">
        {% csrf_token %}
        {% for data in results %}
        <div class="col-md-8 min100 text-justify ">
            <hr>
            <p><b>{{data.title}} </b></p>
            <p>{{data.body}}</p>
            <a href="{% url 'post:list' data.id %}">Ver más</a>
            <a href="{% url 'post:edit' data.id %}">Editar</a>
            <a href="{% url 'post:delete' data.id %}">Eliminar</a>
            <br>
            <br>
        </div>
        {% endfor %}
        
        </form>
    </div>
</div>
<script type="text/javascript">


 
</script>
{% endblock %}
    

templates/blog/post/delete.html
{% extends "base/base.html" %} {% load widget_tweaks %}  {% load static %}
{% block content %}
<div class="container-fluid">
    <h2>Blog  </h2>
    <div class="row">
        <form method="POST" style="width:100%;">
        {% csrf_token %}
        
        <input name="id-delete" id="id-delete" type="hidden" />

        <label>¿Está seguro de eliminar el post seleccionado?</label>
        <a href="{% url 'post:index'%}" class="btn btn-primary">Regresar</a>
        <button class="btn btn-danger" type="submit">ELiminar</button>

        </form>
    </div>
</div>
<script type="text/javascript">
{% if id %}
    $("#id-delete").val('{{id}}');
{% endif %}

 
</script>
{% endblock %}

templates/blog/post/edit.html
{% extends "base/base.html" %} {% load widget_tweaks %}  {% load static %} {% load application_extras %}
{% block content %}
<div class="container-fluid">
    <h2>Editar Post </h2>
    <div class="row">
        <div class="row">
            <form method="POST" style="width:100%;" novalidate>
            {% csrf_token %}
            <br/>
                
			{% for field in form %}
                    <div class="form-group">
                        
                        {% if field|is_textarea %}
                        <div class="col-md-12 min100 {{field.name}} ">
                        {% else %}
                        <div class="col-md-6 min100 {{field.name}} ">

                        {% endif %}           
                        <label for="{{ field.name }}">{{ field.label }} {{ field|is_required:"* "}} </label>                  
                        {{ field|add_class:"form-control"}} 
                       
                        {% for error in field.errors %}
                        <ul>
                            <li class="error">{{error}}</li>
                        </ul>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                <br>
                <div class="col-md-12">
                <a href="{% url 'post:index'%}" class="btn btn-primary">Regresar</a>
                <button class="btn btn-success" type="submit">Actualizar</button>
                </div>
			</form>
        </div>
    </div>
</div>
 <script type="text/javascript">


 
</script>
{% endblock %}
    

templates/blog/post/post.html
{% extends "base/base.html" %} {% load widget_tweaks %}  {% load static %} {% load application_extras %}
{% block content %}
<div class="container-fluid">
    <h2>Nuevo Post </h2>
    <div class="row">
        <div class="row">
            <form method="POST" style="width:100%;" novalidate>
            {% csrf_token %}
            <br/>
                
			{% for field in form %}
                    <div class="form-group">
                        
                        {% if field|is_textarea %}
                        <div class="col-md-12 min100 {{field.name}} ">
                        {% else %}
                        <div class="col-md-6 min100 {{field.name}} ">

                        {% endif %}           
                        <label for="{{ field.name }}">{{ field.label }} {{ field|is_required:"* "}} </label>                  
                        {{ field|add_class:"form-control"}} 
                       
                        {% for error in field.errors %}
                        <ul>
                            <li class="error">{{error}}</li>
                        </ul>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                <br>
                <div class="col-md-12">
                <a href="{% url 'post:index'%}" class="btn btn-primary">Regresar</a>
                <button class="btn btn-success" type="submit">Guardar</button>
                </div>
			</form>
        </div>
    </div>
</div>
<script type="text/javascript">


 
</script>
{% endblock %}
    